#Kartikey Sharma 1001659436
SRC1 = Code4_1001659436.cpp
SRC2 = House.cpp
SRC3 = TrickOrTreater.cpp
OBJ1 = $(SRC1:.cpp=.o)
OBJ2 = $(SRC2:.cpp=.o)
OBJ3 = $(SRC3:.cpp=.o)

EXE = $(SRC1:.cpp=.e)

HFILES = House.h TrickOrTreater.h

CFLAGS = -g -std=c++11 -pthread

all = $(EXE)
 
$(EXE): $(OBJ1) $(OBJ2) $(OBJ3) 
	g++ $(CFLAGS) $(OBJ1) $(OBJ2) $(OBJ3) -o $(EXE) 

$(OBJ1) : $(SRC1) $(HFILES)
	g++ -c $(CFLAGS) $(SRC1) -o $(OBJ1) 
$(OBJ2) : $(SRC2) $(HFILES)
	g++ -c $(CFLAGS) $(SRC2) -o $(OBJ2) 
$(OBJ3) : $(SRC3) $(HFILES)
	g++ -c $(CFLAGS) $(SRC3) -o $(OBJ3) 

